// api/transcript.js — Vercel Serverless Function
// Extracts YouTube transcript server-side (bypasses CORS)

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const { videoId } = req.query;
  if (!videoId || !/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    return res.status(400).json({ error: 'Invalid video ID' });
  }

  try {
    // Step 1: Fetch YouTube page to get caption track URLs
    const ytRes = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      }
    });

    if (!ytRes.ok) throw new Error(`YouTube page fetch failed: ${ytRes.status}`);
    const html = await ytRes.text();

    // Step 2: Extract video title
    let title = '';
    const titleMatch = html.match(/"title":"([^"]{3,200})"/);
    if (titleMatch) {
      title = titleMatch[1].replace(/\\u([0-9a-fA-F]{4})/g, (_, c) =>
        String.fromCharCode(parseInt(c, 16)));
    }

    // Step 3: Find caption tracks in page source
    const capMatch = html.match(/"captionTracks":(\[[\s\S]*?\])/);
    if (!capMatch) {
      return res.status(404).json({
        error: 'NO_TRANSCRIPT',
        title,
        message: 'No transcript available for this video. The creator may have disabled captions, or this video has no auto-generated captions.'
      });
    }

    // Step 4: Parse caption tracks
    let tracks;
    try {
      const cleaned = capMatch[1]
        .replace(/\\u0026/g, '&')
        .replace(/\\\//g, '/');
      tracks = JSON.parse(cleaned);
    } catch (e) {
      throw new Error('Could not parse caption tracks');
    }

    // Step 5: Pick best English track
    const track =
      tracks.find(t => t.languageCode === 'en' && !t.kind) ||
      tracks.find(t => t.languageCode === 'en-US' && !t.kind) ||
      tracks.find(t => t.languageCode === 'en') ||
      tracks.find(t => t.languageCode && t.languageCode.startsWith('en')) ||
      tracks[0];

    if (!track || !track.baseUrl) {
      return res.status(404).json({
        error: 'NO_ENGLISH_TRANSCRIPT',
        title,
        availableLanguages: tracks.map(t => t.languageCode),
        message: 'No English transcript found. Available: ' + tracks.map(t => t.languageCode).join(', ')
      });
    }

    // Step 6: Fetch caption XML
    const captionUrl = track.baseUrl.replace(/\\u0026/g, '&');
    const capRes = await fetch(captionUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      }
    });

    if (!capRes.ok) throw new Error(`Caption fetch failed: ${capRes.status}`);
    const xml = await capRes.text();

    // Step 7: Parse XML to plain text
    const lines = [];
    const regex = /<text[^>]*>([\s\S]*?)<\/text>/g;
    let m;
    while ((m = regex.exec(xml)) !== null) {
      const text = m[1]
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&#39;/g, "'")
        .replace(/&quot;/g, '"')
        .replace(/&nbsp;/g, ' ')
        .replace(/<[^>]+>/g, '')
        .replace(/\n/g, ' ')
        .trim();
      if (text) lines.push(text);
    }

    if (!lines.length) {
      throw new Error('Transcript parsed but was empty');
    }

    const transcript = lines.join(' ').replace(/\s+/g, ' ').trim();

    return res.status(200).json({
      success: true,
      videoId,
      title,
      transcript,
      wordCount: transcript.split(/\s+/).length,
      language: track.languageCode,
      isAutoGenerated: track.kind === 'asr'
    });

  } catch (err) {
    return res.status(500).json({
      error: 'EXTRACTION_FAILED',
      message: err.message
    });
  }
}
