// api/transcript.js — Vercel Serverless Function
// Multi-method YouTube transcript extraction

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const { videoId } = req.query;
  if (!videoId || !/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    return res.status(400).json({ error: 'Invalid video ID' });
  }

  // Method 1: Supadata API (free tier - 100 requests/day)
  try {
    const supaRes = await fetch(
      `https://api.supadata.ai/v1/youtube/transcript?videoId=${videoId}&text=true`,
      { headers: { 'x-api-key': process.env.SUPADATA_API_KEY || '' } }
    );
    if (supaRes.ok) {
      const data = await supaRes.json();
      if (data?.content) {
        const transcript = Array.isArray(data.content)
          ? data.content.map(c => c.text).join(' ')
          : String(data.content);
        return res.status(200).json({
          success: true, videoId, title: data.title || '',
          transcript: transcript.replace(/\s+/g, ' ').trim(),
          wordCount: transcript.split(/\s+/).length,
          language: data.lang || 'en', isAutoGenerated: false
        });
      }
    }
  } catch (_) {}

  // Method 2: Direct YouTube scrape with multiple user agents
  const USER_AGENTS = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0',
  ];

  for (const ua of USER_AGENTS) {
    try {
      const result = await scrapeTranscript(videoId, ua);
      if (result) return res.status(200).json({ success: true, ...result });
    } catch (_) {}
  }

  // All failed
  return res.status(404).json({
    error: 'NO_TRANSCRIPT',
    message: 'Could not extract transcript. The video may not have captions enabled.',
    videoId
  });
}

async function scrapeTranscript(videoId, userAgent) {
  const pageRes = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: {
      'User-Agent': userAgent,
      'Accept-Language': 'en-US,en;q=0.9',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      'Cache-Control': 'no-cache',
      'Pragma': 'no-cache',
    }
  });

  if (!pageRes.ok) return null;
  const html = await pageRes.text();

  // Extract title
  let title = '';
  const titleMatch = html.match(/"title":"([^"]{3,200})"/);
  if (titleMatch) {
    title = titleMatch[1].replace(/\\u([0-9a-fA-F]{4})/g, (_, c) =>
      String.fromCharCode(parseInt(c, 16)));
  }

  // Find caption tracks
  const capMatch = html.match(/"captionTracks":(\[[\s\S]*?\])/);
  if (!capMatch) return null;

  let tracks;
  try {
    tracks = JSON.parse(
      capMatch[1].replace(/\\u0026/g, '&').replace(/\\\//g, '/')
    );
  } catch { return null; }

  if (!tracks?.length) return null;

  const track =
    tracks.find(t => t.languageCode === 'en' && t.kind !== 'asr') ||
    tracks.find(t => t.languageCode === 'en') ||
    tracks.find(t => t.languageCode?.startsWith('en')) ||
    tracks[0];

  if (!track?.baseUrl) return null;

  const captionUrl = track.baseUrl.replace(/\\u0026/g, '&').replace(/\\\//g, '/');
  const capRes = await fetch(captionUrl, { headers: { 'User-Agent': userAgent } });
  if (!capRes.ok) return null;

  const xml = await capRes.text();
  const lines = [];
  const regex = /<text[^>]*>([\s\S]*?)<\/text>/g;
  let m;
  while ((m = regex.exec(xml)) !== null) {
    const text = m[1]
      .replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>')
      .replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ')
      .replace(/<[^>]+>/g,'').replace(/\n/g,' ').trim();
    if (text) lines.push(text);
  }

  if (!lines.length) return null;

  const transcript = lines.join(' ').replace(/\s+/g, ' ').trim();
  return {
    videoId, title, transcript,
    wordCount: transcript.split(/\s+/).length,
    language: track.languageCode,
    isAutoGenerated: track.kind === 'asr'
  };
}
